spring.datasource.url=jdbc:postgresql://localhost:5432/rental_db
spring.datasource.username=md
spring.datasource.password=mdpostgres

# ─── JPA ──────────────────────────────────────────────────────────────────────
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

# ─── Flyway ───────────────────────────────────────────────────────────────────
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
